# NodeJS Version 16
FROM node:20

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install --legacy-peer-deps

# Set Env
ENV NODE_ENV development

EXPOSE 1234

# Cmd script
CMD ["npm", "run", "dev"]
